### PR TITLE
Koa2

### PR DESCRIPTION
**Pull request by omsmith**

### CODE REVIEW

**Comment by tj** [comment]
woot :+1: 

I almost wonder if we should wait for async/await to upgrade middleware, since everyone will probably want to convert them to that after anyway and it's a more direct translation

**Comment by omsmith** [comment]
We could compile ahead of time, but then we're just back to generators (and we may as well just `co.wrap` all of these.

**Comment by tj** [comment]
To me 2.0 is useless until async/await is native, transpiling on the server is just weird if you really don't have to

**Comment by fengmk2** [comment]
It's back to callback style.

Can we make to change to next branch?
If user want to use, publish a new major version like `3.0.0-alpha.1`?

I maintaining a lot of koa@1 applications inside and they're hard to upgrade to koa@2.
I don't think this is the time to use koa@2 ready for most people.

**Comment by tejasmanohar** [comment]
>We could compile ahead of time, but then we're just back to generators (and we may as well just co.wrap all of these.).
I def disagree. Co's built in generator hacky-ness, attempting to fake coroutines with generators (a synchronous feature), and using this for promise-based control flow is meh. Async/await is an actual language feature and is merely a Promise then() handler so there's a huge advantage... it's not at all back to generators ;)

**Comment by omsmith** [comment]
@tejasmanohar I was referring to if we were to use Babel to write these middleware with async/await and publish compiled code, it would be implemented with generators, just as is used today

**Comment by omsmith** [comment]
s/implemented/polyfilled

**Comment by tejasmanohar** [comment]
@omsmith Depends on the settings used. IIRC, Babel can transpile async functions into fake coroutines like Co *or* promise-handling ES5- just depends on the options / presets chosen in v6.

**Comment by omsmith** [comment]
I added a commit that hoists the functions out, just to play with it

**Comment by jonathanong** [comment]
@omsmith there's a lot of style changes here that mess everything up. ex. you have mixed spaces and tabs. please try to avoid doing that next time, but i'll fix it myself this time.

**Comment by jonathanong** [comment]
https://github.com/koajs/etag/compare/v2.x

**Comment by omsmith** [comment]
Hmm, you're quite right - usually notice that. Thanks ;)

**Comment by jonathanong** [comment]
oops it's really this branch https://github.com/koajs/etag/tree/v3.x

**Pull request closed without merging**
