### PR TITLE
fix unit test && support etag options

### PR DESCRIPTION
**Pull request by atian25**

### CODE REVIEW

**Comment by fengmk2** [comment]
ci fail 
image

**Comment by atian25** [comment]
@fengmk2  last commit in my pc is fail too , seem etag result is difference in difference pc.
maybe should not check the whole string

**Comment by atian25** [comment]
@fengmk2 had change to validate etag is exists or start with W/

**Comment by jonathanong** [comment]
might've changed since we last tested this. i'd rather change the etag vs. having a wildcard check

**Comment by atian25** [comment]
@jonathanong the etag is using size and mtime, if using equal, then everytime you modify `package.json`, the etag will change, the test will fail.

```
function stattag(stat) {
  var mtime = stat.mtime.getTime().toString(16)
  var size = stat.size.toString(16)
  return '"' + size + '-' + mtime + '"'
}
```

**Comment by jonathanong** [comment]
ah i see. we can change it to a fixture, but no big deal

**Comment by atian25** [comment]
@jonathanong had changed at this branch, https://travis-ci.org/atian25/etag , but it seems fail at travis, the mtime is difference between my mac and travis.

**Comment by fengmk2** [comment]
LGTM

**Comment by fengmk2** [comment]
@atian25 koa-etag@2.1.0

**Pull request merged**
