### PR TITLE
Update 09 2020

### PR DESCRIPTION
**Pull request by 3imed-jaberi**
- [x] update .gitignore file 🐞
- [x] use standard eslint linter 💅🏻
- [x] update LICENSE 🗝
- [x] use nyc over istanbul for coverage 💯
- [x] update mocha ☕️
- [x] update test code 🧪
- [x] update all deps. 🥡
- [x] update ci pipeline 🎲 
- [x] improve the source code (asyn/await...) ✨
- [x] update README.md 📋
- [x] better pkg.json 🎗
- [x] include #47 😇

**READY TO NEXT RELEASE 🚀**

### CODE REVIEW

**Comment by 3imed-jaberi** [comment]
@jonathanong, @dead-horse, @niftylettuce, @miwnwski ....
you can now merge this then close #47 and go to next release.

**Comment by miwnwski** [comment]
With the engines defined this is a semver major, no?

**Comment by niftylettuce** [comment]
yes, v4.0.0 was just released https://github.com/koajs/etag/releases/tag/v4.0.0

**Comment by 3imed-jaberi** [comment]
@niftylettuce, plz update the History.md file

**Comment by niftylettuce** [comment]
That should be deprecated, as we will now use the Releases tab.

**Pull request merged**
