### PR TITLE
refactor: use lower case etag header

### PR DESCRIPTION
**Pull request by fengmk2**

### CODE REVIEW

**Comment by jonathanong** [comment]
did this break something?

**Comment by fengmk2** [comment]
@jonathanong No, `response.get(header)` will always convert header to lower case. https://github.com/koajs/koa/blob/master/lib/response.js#L417

**Comment by niftylettuce** [comment]
Can I please have npm ownership on this package? `npm owner add niftylettuce koa-charset` cc @jonathanong

**Comment by niftylettuce** [comment]
v4.0.0 was just released https://github.com/koajs/etag/releases/tag/v4.0.0

**Pull request closed without merging**
